### ISSUE TITLE
confirmación de sync + grupos

### ISSUE THREAD

**Issue by montoyamoraga** [FAU-UChile/audiv027-2024-2#105]
hola!

por favor responde esta issue cuando hayas hecho sync en tu fork, y con los nombres de usuario de github de los integrantes de tu grupo (grupos de 2 a 3 personas).

**Comment by BatmanTheDay27** [comment]
04-paltitapaltota y 09-BatmanTheDay27

**Comment by leleleo3** [comment]
confirmo sync :]
integrantes grupo de trabajo: 12-MacNCheese03, 11-leleleo3

**Comment by paltitapaltota** [comment]
confirmo sync y  seré con @BatmanTheDay27

**Comment by sebasebamv** [comment]
confirmo sync @Paola-Garcia24

**Comment by cottito** [comment]
confirmo sync, y somos @cottito @Dielox-X9

**Comment by Dielox-X9** [comment]
confirmo sync, y somos @cottito @Dielox-X9
