### ISSUE TITLE
comentarios proyecto-01 / grupo-04 @paltitapaltota @BatmanTheDay27 

### ISSUE THREAD

**Issue by montoyamoraga** [FAU-UChile/audiv027-2024-2#128]
hola @paltitapaltota y @BatmanTheDay27 

ustedes serán grupo-04 para la próxima semana
cuando tenga comentarios sobre su proyecto los escribiré acá

**Comment by BatmanTheDay27** [comment]
Profe, el link que pusimos al principio no funciona, el que se utiliza para redireccionar al informe principal.

**Comment by paltitapaltota** [comment]
el link que nos dieron en la  pauta que sirve para redireccionar al informe que yo tengo no funciona, esta en el informe para que lo vaya a ver si hay un error de tipeo o de algo
