### ISSUE TITLE
comentarios proyecto-01 / grupo-05 @Paola-Garcia24 @sebasebamv @MauroSSJ24

### ISSUE THREAD

**Issue by montoyamoraga** [FAU-UChile/audiv027-2024-2#129]
hola @Paola-Garcia24 @sebasebamv @MauroSSJ24!

ustedes serán grupo-05 para la próxima semana
cuando tenga comentarios sobre su proyecto los escribiré acá

**Comment by MauroSSJ24** [comment]
Queremos editar los cambios hechos por los compañeros dentro de mi github en la clase 8 y no podemos, sale solo lo editado por mi.
