### ISSUE TITLE
tareas inicio próxima clase

### ISSUE THREAD

**Issue by montoyamoraga** [FAU-UChile/audiv027-2024-2#27]
tengo que explicar branches en GitHub

y tengo que borrar las branches extra de
- @Paola-Garcia24
- @MauroSSJ24
- @MacNCheese03
- @jibbx

y luego tengo que pedir al resto que sincronice
por favor si puedes @vickgit201 recuérdame al inicio :)

**Comment by MauroSSJ24** [comment]
@montoyamoraga profe ya borre mis branches y sincronice. :)

**Comment by MacNCheese03** [comment]
profe tuve un problema con esto y no me salen mis apuntes de la clase 3, además hice lo de las branch y solo tengo una
(si actualicé)

**Comment by montoyamoraga** [comment]
hola @MacNCheese03 
mira tus apuntes de la clase 03 están en mi repo
https://github.com/FAU-UChile/audiv027-2024-2/tree/main/estudiantes/13-MacNCheese03/clase-03
cuando hagas sync fork desde el tuyo, vas a recuperar tus apuntes :)
