### ISSUE TITLE
Asistencia Clase 4

### ISSUE THREAD

**Issue by vickgit201** [FAU-UChile/audiv027-2024-2#36]
Por favor responder y etiquetar a @montoyamoraga y a @vickgit201

**Comment by MacNCheese03** [comment]
estoy!

**Comment by marcegato** [comment]
Estoy @montoyamoraga @vickgit201

**Comment by paltitapaltota** [comment]
estoy @montoyamoraga @vickgit201

**Comment by sebasebamv** [comment]
estoy  @montoyamoraga @vickgit201

**Comment by leleleo3** [comment]
existo @vickgit201 @montoyamoraga

**Comment by cottito** [comment]
alo @vickgit201 @montoyamoraga

**Comment by valen288** [comment]
Hola! @vickgit201 @montoyamoraga

**Comment by Niquito2010** [comment]
Holaa! @vickgit201 @montoyamoraga

**Comment by Paola-Garcia24** [comment]
Hola! @vickgit201 @montoyamoraga

**Comment by Dielox-X9** [comment]
Hola! @vickgit201 @montoyamoraga
