### ISSUE TITLE
confirmar que sus repos están sync

### ISSUE THREAD

**Issue by montoyamoraga** [FAU-UChile/audiv027-2024-2#68]
etiquetarme a mi handle @montoyamoraga

**Comment by paltitapaltota** [comment]
si lo actualice

**Comment by leleleo3** [comment]
confirmo @montoyamoraga

**Comment by MacNCheese03** [comment]
Profe subí unos apuntes de la clase que no vine. Podría por favor integrarlo para estar en sync. Gracias !

**Comment by Dielox-X9** [comment]
@montoyamoraga Actualizado para uno nueva clase 😄

**Comment by BatmanTheDay27** [comment]
confirmado @montoyamoraga 😄

**Comment by Vixo46** [comment]
Confirmado @montoyamoraga =)

**Comment by Niquito2010** [comment]
Confirmado @montoyamoraga :)

**Comment by Dielox-X9** [comment]
@montoyamoraga Me podría actualizar unas modificaciones que realicé en la Clase 5, Porfavor

**Comment by MacNCheese03** [comment]
ahora si profe gracias! @montoyamoraga

**Comment by cottito** [comment]
sí lo actualicé @montoyamoraga

**Comment by MauroSSJ24** [comment]
confirmo @montoyamoraga
